[REWORKING]
[H[2J[3J[REMOVING] /Users/tmaluh/RT/objects
[REMOVING] RT
[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3Jmake[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3Jmake[3]: `libminifb.a' is up to date.
make[2]: Nothing to be done for `all'.
[CREATING]	RT	[VANILLA-OPTIMIZE]
[COMPILING]	/Darwin/sanitize.c
[COMPILING]	/Generic/main.c
[COMPILING]	/Generic/bvh/aabb/aabb.c
[COMPILING]	/Generic/camera/camera_ray/camera_ray.c
[COMPILING]	/Generic/camera/constructor/camera_constructor.c
[COMPILING]	/Generic/hitable/color/color.c
[COMPILING]	/Generic/hitable/cone/constructor/cone_vector.c
[COMPILING]	/Generic/hitable/cylinder/constructor/cylinder_vector.c
[COMPILING]	/Generic/hitable/hit/hit.c
[COMPILING]	/Generic/hitable/plane/constructor/plane_vector.c
[COMPILING]	/Generic/hitable/record/record.c
[COMPILING]	/Generic/hitable/record/record_general.c
[COMPILING]	/Generic/hitable/record/condition/record_condition.c
[COMPILING]	/Generic/hitable/record/iter/record_iter.c
[COMPILING]	/Generic/hitable/record/material/record_material.c
[COMPILING]	/Generic/hitable/record/normal/record_normal.c
[COMPILING]	/Generic/hitable/record/point/record_point.c
[COMPILING]	/Generic/hitable/sphere/center/center.c
[COMPILING]	/Generic/hitable/sphere/constructor/sphere_struct.c
[COMPILING]	/Generic/hitable/sphere/constructor/sphere_vector.c
[COMPILING]	/Generic/hitable/sphere/discriminant/discriminant.c
[COMPILING]	/Generic/hitable/sphere/hit/sphere_hit.c
[COMPILING]	/Generic/hitable/sphere/radius/radius.c
[COMPILING]	/Generic/hitable/tetrahedron/constructor/tetrahedron_vector.c
[COMPILING]	/Generic/material/albedo/albedo.c
[COMPILING]	/Generic/material/constructor/material_constructor.c
[COMPILING]	/Generic/material/fuzz/fuzz.c
[COMPILING]	/Generic/material/ri/ri.c
[COMPILING]	/Generic/material/scatter/scatter.c
[COMPILING]	/Generic/material/type/type.c
[COMPILING]	/Generic/parser/free_scene.c
[COMPILING]	/Generic/parser/parser.c
[COMPILING]	/Generic/parser/sp_render_camera.c
[COMPILING]	/Generic/parser/arr_to_vec/sp_arr_to_v3sf.c
[COMPILING]	/Generic/random/random_float.c
[COMPILING]	/Generic/random/u32_random/u32_rand.c
[COMPILING]	/Generic/ray/constructor/ray_struct.c
[COMPILING]	/Generic/ray/constructor/ray_vector.c
[COMPILING]	/Generic/ray/direction/direction.c
[COMPILING]	/Generic/ray/origin/origin.c
[COMPILING]	/Generic/ray/point_at_parameter/point_at_parameter_v3df.c
[COMPILING]	/Generic/ray/point_at_parameter/point_at_parameter_v3sf.c
[COMPILING]	/Generic/render/render.c
[COMPILING]	/Generic/render/color_to_rgb/color_to_rgb.c
[COMPILING]	/Generic/scene_generator/scene_generator.c
[COMPILING]	/Generic/thread_pool/thread_pool.c
[COMPILING]	/Generic/vector/constructor/vec2.c
[COMPILING]	/Generic/vector/constructor/vec3.c
[COMPILING]	/Generic/vector/constructor/vec4.c
[COMPILING]	/Generic/vector/cross/cross2.c
[COMPILING]	/Generic/vector/cross/cross3.c
[COMPILING]	/Generic/vector/dot/dot2.c
[COMPILING]	/Generic/vector/dot/dot3.c
[COMPILING]	/Generic/vector/dot/dot4.c
[COMPILING]	/Generic/vector/length/length2.c
[COMPILING]	/Generic/vector/length/length3.c
[COMPILING]	/Generic/vector/length/length4.c
[COMPILING]	/Generic/vector/length_squared/length_squared2.c
[COMPILING]	/Generic/vector/length_squared/length_squared3.c
[COMPILING]	/Generic/vector/length_squared/length_squared4.c
[COMPILING]	/Generic/vector/normalize/normalize2.c
[COMPILING]	/Generic/vector/normalize/normalize3.c
[COMPILING]	/Generic/vector/normalize/normalize4.c
[COMPILING]	/Generic/vector/reduce_add/reduce_add2.c
[COMPILING]	/Generic/vector/reduce_add/reduce_add3.c
[COMPILING]	/Generic/vector/reduce_add/reduce_add4.c
[COMPILING]	/Generic/vector/reflect/reflect2.c
[COMPILING]	/Generic/vector/reflect/reflect3.c
[COMPILING]	/Generic/vector/reflect/reflect4.c
[COMPILING]	/Generic/vector/refract/refract2.c
[COMPILING]	/Generic/vector/refract/refract3.c
[COMPILING]	/Generic/vector/refract/refract4.c
[COMPILING]	/Generic/vector/refract_cond/refract_cond2.c
[COMPILING]	/Generic/vector/refract_cond/refract_cond3.c
[COMPILING]	/Generic/vector/refract_cond/refract_cond4.c
[COMPILING]	/Generic/vector/refract_do/refract_do2.c
[COMPILING]	/Generic/vector/refract_do/refract_do3.c
[COMPILING]	/Generic/vector/refract_do/refract_do4.c
[COMPILING]	/Generic/vector/refract_reflect/refract_reflect2.c
[COMPILING]	/Generic/vector/refract_reflect/refract_reflect3.c
[COMPILING]	/Generic/vector/refract_reflect/refract_reflect4.c
[COMPILING]	/Generic/vector/rsqroot/rsqroot1.c
[COMPILING]	/Generic/vector/rsqroot/rsqroot2.c
[COMPILING]	/Generic/vector/rsqroot/rsqroot3.c
[COMPILING]	/Generic/vector/rsqroot/rsqroot4.c
[COMPILING]	/Generic/vector/sqroot/sqroot1.c
[COMPILING]	/Generic/vector/sqroot/sqroot2.c
[COMPILING]	/Generic/vector/sqroot/sqroot3.c
[COMPILING]	/Generic/vector/sqroot/sqroot4.c
[COMPILING]	/Generic/vector/vec_dot/vec_dot2.c
[COMPILING]	/Generic/vector/vec_dot/vec_dot3.c
[COMPILING]	/Generic/vector/vec_dot/vec_dot4.c
[COMPILING]	/Generic/vector/vec_length_squared/vec_length_squared2.c
[COMPILING]	/Generic/vector/vec_length_squared/vec_length_squared3.c
[COMPILING]	/Generic/vector/vec_length_squared/vec_length_squared4.c
[COMPILING]	/Generic/vector/vec_reduce_add/vec_reduce_add2.c
[COMPILING]	/Generic/vector/vec_reduce_add/vec_reduce_add3.c
[COMPILING]	/Generic/vector/vec_reduce_add/vec_reduce_add4.c
